In [24]:
import numpy as np 
from sklearn.datasets import load_digits
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix
from sklearn.decomposition import PCA

In [25]:
d = load_digits()

data = d.data
tar = d.target

x1 = data+np.random.normal(scale=1, size=data.shape)
y1 = KMeans(10).fit_predict(x1)

matx = confusion_matrix(tar,y1)
a = np.trace(matx)/np.sum(matx)
print('confusion matrix', matx)
print('Accuracy of Noised dataset :', a)

p = PCA(2)
x2 = p.fit_transform(x1)
y2 = KMeans(10).fit_predict(x2)

matx = confusion_matrix(y,y2)
a = np.trace(matx)/np.sum(matx)

print('confusion matrix',matx)
print('Accuracy after using PCA :',a)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


confusion matrix [[  0   0 176   0   0   2   0   0   0   0]
 [  1 100   0  54   1   0   0   2   0  24]
 [ 12   7   1   3   0   0   3   0   4 147]
 [154   7   0   0   2   0  11   0   7   2]
 [  0   3   0   4   0 165   0   0   9   0]
 [  2   0   0   0 134   1  44   1   0   0]
 [  0   2   1   1   0   0   0 177   0   0]
 [  0   2   0   2   0   0   0   0 175   0]
 [  2  99   1   6   5   0  53   2   3   3]
 [  7   1   0  20   4   0 139   0   9   0]]
Accuracy of Noised dataset : 0.05843071786310518
confusion matrix [[ 17  12  21  16  42  23  17  14   6  10]
 [161 180 158 155 186 178 165 193 134 109]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]]
Accuracy after using PCA : 0.10962715637173066


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
